default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: amazon_tracker_development

test:
  <<: *default
  database: amazon_tracker_test


production:
  <<: *default
  database: amazon_tracker_production
